# Type stubs for PyQt6
from typing import Any, Optional, Union

class QWidget:
    def __init__(self, parent: Optional['QWidget'] = None) -> None: ...
    def mapToGlobal(self, point: 'QPoint') -> 'QPoint': ...

class QPoint:
    def __init__(self, x: int = 0, y: int = 0) -> None: ...

class QApplication:
    def __init__(self, argv: list[str]) -> None: ...
